#!/usr/bin/env python3
"""
TeamForge IDE Instruction Manual — PDF Generator
Generates a professional instruction manual using ReportLab (body) + HTML/Playwright (cover)
"""

import hashlib
import os
import subprocess
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm, inch
from reportlab.lib.utils import simpleSplit
from reportlab.platypus import (
    CondPageBreak,
    KeepTogether,
    PageBreak,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.platypus import SimpleDocTemplate
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
# Contrast: text:bg=14.41 | accent:bg=4.52
ACCENT       = colors.HexColor('#23748f')
TEXT_PRIMARY  = colors.HexColor('#1d1d1b')
TEXT_MUTED    = colors.HexColor('#7c7970')
BG_SURFACE   = colors.HexColor('#e6e3db')
BG_PAGE       = colors.HexColor('#eeede9')
SURFACE_RGBA = 'rgba(0,0,0,0.02)'

# ReportLab table colors
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Page Dimensions ━━
PAGE_W, PAGE_H = A4  # 595.28 x 841.89
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_W = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

OUTPUT_DIR = Path('/home/z/my-project')
BODY_PDF = OUTPUT_DIR / 'teamforge_body.pdf'
COVER_HTML = OUTPUT_DIR / 'teamforge_cover.html'
COVER_PDF = OUTPUT_DIR / 'teamforge_cover.pdf'
FINAL_PDF = OUTPUT_DIR / 'TeamForge_Instruction_Manual.pdf'

SKILL_DIR = Path('/tmp/my-project/skills/pdf')

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSansBook', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('FreeSans', '/usr/share/fonts/truetype/freefont/FreeSans.ttf'))
pdfmetrics.registerFont(TTFont('FreeSansBold', '/usr/share/fonts/truetype/freefont/FreeSansBold.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('LiberationSans', normal='LiberationSans', bold='LiberationSans-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('FreeSans', normal='FreeSans', bold='FreeSansBold')
registerFontFamily('SarasaMonoSC', normal='SarasaMonoSC', bold='SarasaMonoSC')

# ━━ Paragraph Styles ━━
BODY_FONT = 'LiberationSerif'
CODE_FONT = 'DejaVuSans'

style_h1 = ParagraphStyle(
    name='H1', fontName=BODY_FONT, fontSize=20, leading=28,
    textColor=ACCENT, spaceBefore=18, spaceAfter=10,
)
style_h2 = ParagraphStyle(
    name='H2', fontName=BODY_FONT, fontSize=14, leading=20,
    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8,
)
style_h3 = ParagraphStyle(
    name='H3', fontName=BODY_FONT, fontSize=12, leading=17,
    textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6,
)
style_body = ParagraphStyle(
    name='Body', fontName=BODY_FONT, fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=6,
)
style_body_left = ParagraphStyle(
    name='BodyLeft', fontName=BODY_FONT, fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=6,
)
style_bullet = ParagraphStyle(
    name='Bullet', fontName=BODY_FONT, fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, leftIndent=18, bulletIndent=6,
    spaceAfter=4, alignment=TA_LEFT,
)
style_bullet2 = ParagraphStyle(
    name='Bullet2', fontName=BODY_FONT, fontSize=10, leading=16,
    textColor=TEXT_PRIMARY, leftIndent=36, bulletIndent=24,
    spaceAfter=3, alignment=TA_LEFT,
)
style_code = ParagraphStyle(
    name='Code', fontName=CODE_FONT, fontSize=9, leading=14,
    textColor=colors.HexColor('#2d2d2d'),
    backColor=colors.HexColor('#f4f4f0'),
    leftIndent=12, rightIndent=12,
    spaceBefore=4, spaceAfter=4,
    borderWidth=0.5, borderColor=BG_SURFACE, borderPadding=6,
)
style_table_header = ParagraphStyle(
    name='TH', fontName=BODY_FONT, fontSize=10, leading=14,
    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER,
)
style_table_cell = ParagraphStyle(
    name='TC', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
style_table_cell_c = ParagraphStyle(
    name='TCC', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER,
)
style_table_code = ParagraphStyle(
    name='TCode', fontName=CODE_FONT, fontSize=8.5, leading=13,
    textColor=colors.HexColor('#2d2d2d'), alignment=TA_LEFT,
)
style_caption = ParagraphStyle(
    name='Caption', fontName=BODY_FONT, fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_CENTER,
    spaceBefore=3, spaceAfter=6,
)
style_toc1 = ParagraphStyle(
    name='TOC1', fontName=BODY_FONT, fontSize=13, leading=22,
    leftIndent=20,
)
style_toc2 = ParagraphStyle(
    name='TOC2', fontName=BODY_FONT, fontSize=11, leading=18,
    leftIndent=40,
)

# ━━ TOC Document Template ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ━━ Heading Helpers ━━
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_major_section(text):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style_h1, level=0),
    ]

def add_subsection(text):
    return [add_heading(text, style_h2, level=1)]

def add_subsubsection(text):
    return [add_heading(text, style_h3, level=1)]

# ━━ Table Helper ━━
def make_table(headers, rows, col_widths=None, caption=None):
    """Build a professional table with palette colors and Paragraph-wrapped cells."""
    data = []
    header_row = [Paragraph('<b>%s</b>' % h, style_table_header) for h in headers]
    data.append(header_row)
    for row in rows:
        data.append([Paragraph(str(c), style_table_cell) if not isinstance(c, Paragraph) else c for c in row])

    if col_widths is None:
        n = len(headers)
        col_widths = [AVAILABLE_W / n] * n
    else:
        total = sum(col_widths)
        if total < AVAILABLE_W * 0.85:
            scale = (AVAILABLE_W * 0.95) / total
            col_widths = [w * scale for w in col_widths]

    tbl = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))

    elements = [Spacer(1, 18), tbl]
    if caption:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption, style_caption))
    elements.append(Spacer(1, 12))
    return elements

def make_code_table(headers, rows, col_widths=None, caption=None):
    """Table where second column uses monospace font for code/commands."""
    data = []
    header_row = [Paragraph('<b>%s</b>' % h, style_table_header) for h in headers]
    data.append(header_row)
    for row in rows:
        cells = []
        for i, c in enumerate(row):
            if i == 0 and len(headers) > 1:
                cells.append(Paragraph(str(c), style_table_code))
            else:
                cells.append(Paragraph(str(c), style_table_cell) if not isinstance(c, Paragraph) else c)
        data.append(cells)

    if col_widths is None:
        n = len(headers)
        col_widths = [AVAILABLE_W / n] * n
    else:
        total = sum(col_widths)
        if total < AVAILABLE_W * 0.85:
            scale = (AVAILABLE_W * 0.95) / total
            col_widths = [w * scale for w in col_widths]

    tbl = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))

    elements = [Spacer(1, 18), tbl]
    if caption:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption, style_caption))
    elements.append(Spacer(1, 12))
    return elements

def bullet(text):
    return Paragraph(text, style_bullet)

def bullet2(text):
    return Paragraph(text, style_bullet2)

def body(text):
    return Paragraph(text, style_body)

def body_left(text):
    return Paragraph(text, style_body_left)

def code_block(text):
    return Paragraph(text, style_code)

# ━━ COVER HTML ━━
def generate_cover_html():
    """Generate cover HTML using Template 01 HUD Data Terminal layout."""
    accent_hex = '#23748f'
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800;900&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
<style>
@page {{
  size: 794px 1123px;
  margin: 0;
}}
html, body {{
  margin: 0; padding: 0;
  width: 794px; height: 1123px;
  background: #ffffff;
  font-family: 'Inter', sans-serif;
  overflow: hidden;
}}
.cover {{
  position: relative;
  width: 794px;
  height: 1123px;
  overflow: hidden;
}}
/* Layer 1: Background grid */
.bg-grid {{
  position: absolute;
  inset: 0;
  overflow: hidden;
  z-index: 1;
}}
.bg-grid-line-h {{
  position: absolute;
  left: 0; right: 0;
  height: 0.5pt;
  background: {accent_hex};
  opacity: 0.03;
}}
.bg-grid-line-v {{
  position: absolute;
  top: 0; bottom: 0;
  width: 0.5pt;
  background: {accent_hex};
  opacity: 0.03;
}}
/* Layer 2: Structure */
.anchor-line {{
  position: absolute;
  left: 12%; top: 10%;
  width: 6pt; height: 80%;
  background: {accent_hex};
  z-index: 2;
  border-radius: 3pt;
}}
.meta-separator {{
  position: absolute;
  left: calc(12% + 30px);
  bottom: 24%;
  width: 40%;
  height: 1pt;
  background: {accent_hex};
  opacity: 0.4;
  z-index: 2;
}}
/* Layer 3: Content */
.kicker {{
  position: absolute;
  left: calc(12% + 30px);
  top: 15%;
  font-size: 16pt;
  font-weight: 400;
  letter-spacing: 3pt;
  color: {accent_hex};
  opacity: 0.6;
  text-transform: uppercase;
  z-index: 3;
}}
.hero-title {{
  position: absolute;
  left: calc(12% + 30px);
  top: 30%;
  font-family: 'Playfair Display', serif;
  font-size: 56pt;
  font-weight: 900;
  color: {accent_hex};
  line-height: 1.15;
  z-index: 3;
}}
.summary {{
  position: absolute;
  left: calc(12% + 30px);
  top: 52%;
  width: 55%;
  font-size: 16pt;
  font-weight: 400;
  line-height: 1.6;
  color: {accent_hex};
  opacity: 0.85;
  z-index: 3;
}}
.meta-block {{
  position: absolute;
  left: calc(12% + 30px);
  bottom: 12%;
  font-size: 18pt;
  font-weight: 400;
  color: {accent_hex};
  opacity: 0.75;
  line-height: 1.8;
  z-index: 3;
}}
</style>
</head>
<body>
<div class="cover">
  <!-- Layer 1: Background grid -->
  <div class="bg-grid">
    {''.join(f'<div class="bg-grid-line-h" style="top:{i*50}px"></div>' for i in range(1, 23))}
    {''.join(f'<div class="bg-grid-line-v" style="left:{i*50}px"></div>' for i in range(1, 16))}
  </div>
  <!-- Layer 2: Structure -->
  <div class="anchor-line"></div>
  <div class="meta-separator"></div>
  <!-- Layer 3: Content -->
  <div class="kicker">Instruction Manual</div>
  <div class="hero-title">TeamForge<br>IDE</div>
  <div class="summary">
    A comprehensive guide to the autonomous agentic IDE featuring
    multi-agent AI orchestration, context-aware chat, intelligent code editing,
    and integrated project management for modern software development.
  </div>
  <div class="meta-block">
    Version v1.0.0<br>
    March 2026
  </div>
</div>
</body>
</html>"""
    COVER_HTML.write_text(html, encoding='utf-8')
    print(f"Cover HTML written to {COVER_HTML}")


# ━━ BUILD BODY PDF ━━
def build_body_pdf():
    doc = TocDocTemplate(
        str(BODY_PDF),
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title='TeamForge IDE Instruction Manual',
        author='Z.ai',
        creator='Z.ai',
    )

    story = []

    # ─── TABLE OF CONTENTS ───
    story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle(
        name='TOCTitle', fontName=BODY_FONT, fontSize=22, leading=30,
        textColor=ACCENT, spaceBefore=12, spaceAfter=18, alignment=TA_LEFT,
    )))
    toc = TableOfContents()
    toc.levelStyles = [style_toc1, style_toc2]
    story.append(toc)
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════
    # SECTION 1: Introduction
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('1. Introduction'))

    story.extend(add_subsection('1.1 What is TeamForge IDE?'))
    story.append(body(
        'TeamForge IDE is a next-generation autonomous agentic integrated development environment '
        'designed to revolutionize software development workflows. Built with a modern web-based '
        'architecture using Next.js, React, and Tailwind CSS, it combines the power of multiple '
        'specialized AI agents with a full-featured code editor, context-aware chat system, and '
        'comprehensive project management tools. Unlike traditional IDEs that rely solely on '
        'human input, TeamForge IDE leverages a team of six AI agents that collaborate autonomously '
        'to plan, architect, develop, review, test, and deploy code.'
    ))

    story.extend(add_subsection('1.2 Key Features'))
    features = [
        '<b>Multi-Agent AI System</b> -- Six specialized agents (Nova, Atlas, Codey, Prism, Flux, Blaze) work collaboratively on tasks, each with distinct roles covering the full software development lifecycle.',
        '<b>Context-Aware AI Chat</b> -- The chat system understands project structure, active files, dependencies, and build output to provide highly relevant assistance. Supports multiple AI providers including Z-AI, NVIDIA NIM, and OpenAI-compatible endpoints.',
        '<b>Intelligent Code Editor</b> -- A multi-file editor with syntax highlighting, find and replace, go-to-line navigation, and the ability to run files directly with automatic language detection.',
        '<b>Project Management</b> -- Integrated task board with six status columns, priority levels, task types, and automatic agent assignment based on task type and agent specialization.',
        '<b>Interactive Terminal</b> -- Execute commands directly within the IDE with build, lint, and test integration, pre-deploy checks, and a command whitelist for safety.',
        '<b>Virtual File System</b> -- Full file and directory management within the browser, supporting create, edit, delete, and batch operations without requiring local file system access.',
    ]
    for f in features:
        story.append(bullet(f))

    story.extend(add_subsection('1.3 System Requirements'))
    story.extend(make_table(
        ['Requirement', 'Specification'],
        [
            ['Node.js', '18.x or later'],
            ['Bun Runtime', '1.x or later (recommended)'],
            ['Database', 'PostgreSQL (via Prisma ORM)'],
            ['Operating System', 'Linux, macOS, or Windows with WSL2'],
            ['Memory', 'Minimum 4 GB RAM (8 GB recommended)'],
            ['Disk Space', '500 MB for application + dependencies'],
            ['Browser', 'Chrome 90+, Firefox 88+, Safari 14+, Edge 90+'],
        ],
        col_widths=[AVAILABLE_W * 0.35, AVAILABLE_W * 0.60],
        caption='Table 1: System Requirements',
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 2: Getting Started
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('2. Getting Started'))

    story.extend(add_subsection('2.1 Installation'))
    story.append(body('TeamForge IDE can be set up locally by following these steps:'))
    steps = [
        '<b>Clone the repository:</b> git clone the project repository to your local machine.',
        '<b>Install dependencies:</b> Run <font name="DejaVuSans">bun install</font> to install all required packages.',
        '<b>Initialize the database:</b> Run <font name="DejaVuSans">bun run db:push</font> to set up the PostgreSQL schema via Prisma.',
        '<b>Start the development server:</b> Run <font name="DejaVuSans">bun run dev</font> to launch the application.',
    ]
    for i, s in enumerate(steps, 1):
        story.append(bullet(f'{i}. {s}'))
    story.append(Spacer(1, 6))
    story.append(code_block(
        '$ git clone &lt;repository-url&gt;<br/>'
        '$ cd teamforge-ide<br/>'
        '$ bun install<br/>'
        '$ bun run db:push<br/>'
        '$ bun run dev'
    ))

    story.extend(add_subsection('2.2 First Launch'))
    story.append(body(
        'Upon first launch, the application opens in your default web browser at '
        '<font name="DejaVuSans">http://localhost:3000</font>. The initial view presents the '
        'dashboard with the sidebar navigation on the left, the main workspace area in the center, '
        'and the AI chat panel on the right. You will see the six AI agents displayed in the '
        'sidebar, each in an idle state, ready to begin work.'
    ))

    story.extend(add_subsection('2.3 Interface Overview'))
    story.append(body(
        'The TeamForge IDE interface is organized into a three-column layout that maximizes '
        'productivity by keeping all essential tools visible simultaneously:'
    ))
    layout_items = [
        '<b>Left Sidebar:</b> Contains the file explorer (virtual file system), AI agents panel, task board, and navigation between different workspace views including dashboard, agents, tasks, chat, terminal, and settings.',
        '<b>Center Editor:</b> The main workspace area features a tabbed code editor with syntax highlighting, breadcrumb navigation, find and replace functionality, and a bottom panel for terminal output, build logs, and system logs.',
        '<b>Right Chat Panel:</b> The AI chat interface provides context-aware assistance with support for slash commands, multi-session management, and real-time streaming responses from your selected AI provider.',
    ]
    for item in layout_items:
        story.append(bullet(item))

    # ═══════════════════════════════════════════════════
    # SECTION 3: AI Agents
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('3. AI Agents'))

    story.extend(add_subsection('3.1 Overview of the Six Agents'))
    story.append(body(
        'TeamForge IDE employs six specialized AI agents, each designed to handle a specific '
        'aspect of the software development lifecycle. These agents collaborate through an '
        'orchestration system that assigns tasks, manages dependencies, and ensures smooth '
        'handoffs between phases.'
    ))

    story.extend(make_table(
        ['Agent', 'Role', 'Responsibilities'],
        [
            ['Nova', 'Project Manager', 'Task planning, prioritization, resource allocation, and project coordination. Breaks down requirements into actionable tasks.'],
            ['Atlas', 'Architect', 'System design, technical architecture decisions, technology selection, and design pattern recommendations.'],
            ['Codey', 'Developer', 'Code implementation, feature development, bug fixes, and technical debt resolution. The primary code-writing agent.'],
            ['Prism', 'Reviewer', 'Code review, quality assurance, best practices enforcement, and security vulnerability detection.'],
            ['Flux', 'Tester', 'Test creation, test execution, coverage analysis, and regression detection. Ensures code reliability.'],
            ['Blaze', 'DevOps', 'Deployment automation, infrastructure management, CI/CD pipeline configuration, and monitoring setup.'],
        ],
        col_widths=[AVAILABLE_W * 0.10, AVAILABLE_W * 0.18, AVAILABLE_W * 0.67],
        caption='Table 2: AI Agent Overview',
    ))

    story.extend(add_subsection('3.2 Agent Statuses'))
    story.append(body(
        'Each agent can be in one of several states, providing real-time visibility into '
        'their current activity and availability:'
    ))
    story.extend(make_table(
        ['Status', 'Description', 'Visual Indicator'],
        [
            ['Idle', 'Agent is available and waiting for task assignment', 'Gray dot'],
            ['Thinking', 'Agent is processing a task or analyzing code', 'Pulsing yellow dot'],
            ['Coding', 'Agent is actively writing or modifying code', 'Green dot'],
            ['Reviewing', 'Agent is reviewing code for quality and correctness', 'Blue dot'],
            ['Testing', 'Agent is creating or executing tests', 'Orange dot'],
            ['Deploying', 'Agent is managing deployment operations', 'Purple dot'],
            ['Sleeping', 'Agent is inactive due to inactivity timeout', 'Dimmed gray dot'],
        ],
        col_widths=[AVAILABLE_W * 0.15, AVAILABLE_W * 0.55, AVAILABLE_W * 0.25],
        caption='Table 3: Agent Status States',
    ))

    story.extend(add_subsection('3.3 Agent Detail Dialog'))
    story.append(body(
        'Clicking on any agent opens the Agent Detail Dialog, which provides comprehensive '
        'information about the selected agent including: current status and active task, '
        'task history and completion statistics, specialized capabilities and preferred task types, '
        'recent activity log with timestamps, and performance metrics such as average task '
        'completion time and success rate.'
    ))

    story.extend(add_subsection('3.4 YOLO Mode'))
    story.append(body(
        'YOLO Mode is TeamForge IDE\'s full autonomy mode. When activated, the AI agents '
        'operate with minimal human oversight, automatically proceeding through the entire '
        'development lifecycle from planning to deployment. In YOLO Mode: Nova plans and assigns '
        'tasks automatically, Atlas makes architectural decisions independently, Codey implements '
        'features without requiring approval for each change, Prism performs code reviews and '
        'can approve changes autonomously, Flux runs tests and reports results, and Blaze handles '
        'deployment when all quality gates pass.'
    ))
    story.append(body(
        '<b>Warning:</b> YOLO Mode is intended for experienced users who trust the AI system. '
        'It is recommended to use standard mode for critical production code and enable YOLO Mode '
        'only for prototyping, experimentation, or well-tested workflows.'
    ))

    story.extend(add_subsection('3.5 Agent Orchestrator and Scheduler'))
    story.append(body(
        'The Agent Orchestrator is the central coordination system that manages task assignment '
        'and inter-agent communication. It operates through the following mechanisms:'
    ))
    orch_items = [
        '<b>Task Assignment:</b> Automatically assigns tasks to the most appropriate agent based on task type, agent specialization, and current workload.',
        '<b>Dependency Management:</b> Tracks task dependencies and ensures that prerequisite tasks are completed before dependent tasks begin.',
        '<b>Handoff Protocol:</b> Manages smooth transitions between agents, passing context and artifacts (code, test results, review comments) between phases.',
        '<b>Conflict Resolution:</b> Handles situations where multiple agents need to modify the same file simultaneously through a locking and merging mechanism.',
        '<b>Scheduler:</b> The agent scheduler API endpoint allows external systems to trigger agent actions, schedule periodic tasks, and monitor agent health.',
    ]
    for item in orch_items:
        story.append(bullet(item))

    # ═══════════════════════════════════════════════════
    # SECTION 4: AI Chat System
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('4. AI Chat System'))

    story.extend(add_subsection('4.1 Context-Aware AI'))
    story.append(body(
        'The AI chat system in TeamForge IDE is deeply integrated with your project context. '
        'Unlike generic chat interfaces, it automatically incorporates the following context '
        'into every conversation:'
    ))
    ctx_items = [
        '<b>Project Structure:</b> The chat engine understands your entire project layout, including file hierarchy, directory conventions, and module organization.',
        '<b>Active File:</b> The currently open file in the editor is automatically included in the chat context, allowing the AI to reference and modify it directly.',
        '<b>Dependencies:</b> Package dependencies from package.json and other configuration files are considered when providing recommendations or generating code.',
        '<b>Build Output:</b> Recent build errors, warnings, and test results are available to the AI for debugging and fix suggestions.',
    ]
    for item in ctx_items:
        story.append(bullet(item))

    story.extend(add_subsection('4.2 Multi-Provider Support'))
    story.append(body(
        'TeamForge IDE supports three categories of AI providers, offering flexibility '
        'in choosing the model that best fits your needs and budget:'
    ))
    story.extend(make_table(
        ['Provider', 'Models', 'Key Features'],
        [
            ['Z-AI', 'GLM-4, GLM-4 Flash', 'Optimized for code generation and analysis. Low latency with Flash variant.'],
            ['NVIDIA NIM', '80+ models', 'Access to Meta Llama, NVIDIA Nemotron, DeepSeek, Mistral, Qwen, Gemma, Phi, and more.'],
            ['OpenAI-Compatible', 'Varies by endpoint', 'Connect to Ollama, LM Studio, vLLM, Together AI, or any OpenAI-compatible API.'],
        ],
        col_widths=[AVAILABLE_W * 0.17, AVAILABLE_W * 0.23, AVAILABLE_W * 0.55],
        caption='Table 4: AI Provider Overview',
    ))

    story.extend(add_subsection('4.3 Chat Sessions'))
    story.append(body(
        'The chat system supports multiple concurrent sessions, each with its own context and history:'
    ))
    session_items = [
        '<b>Create Session:</b> Start a new chat session from the chat panel header. Each session maintains independent conversation history.',
        '<b>Rename Session:</b> Double-click the session name to rename it for easy identification.',
        '<b>Switch Session:</b> Click on any session in the session list to switch to it. Context is preserved between switches.',
        '<b>Delete Session:</b> Remove a session and its entire history using the delete action in the session menu.',
    ]
    for item in session_items:
        story.append(bullet(item))

    story.extend(add_subsection('4.4 Slash Commands'))
    story.append(body(
        'Slash commands provide quick access to common AI-powered operations directly from '
        'the chat input. Type a forward slash (/) to see the available commands:'
    ))
    story.extend(make_code_table(
        ['Command', 'Description'],
        [
            ['/run', 'Execute the current file or a specified command'],
            ['/edit', 'Request AI-assisted code editing on the active file'],
            ['/fix', 'Automatically diagnose and fix errors in the current file'],
            ['/refactor', 'Refactor the selected code for improved readability and maintainability'],
            ['/optimize', 'Optimize code performance based on AI analysis'],
            ['/search', 'Search across the entire project for patterns, files, or code'],
            ['/commit', 'Generate a commit message and stage changes for version control'],
            ['/explain', 'Get a detailed explanation of the selected or current code'],
            ['/status', 'Display current project status, agent states, and task progress'],
            ['/deploy', 'Initiate deployment through Blaze (DevOps agent)'],
            ['/build', 'Run the project build pipeline and display results'],
            ['/test', 'Execute the test suite and display coverage results'],
            ['/create_file', 'Create a new file with AI-generated boilerplate content'],
        ],
        col_widths=[AVAILABLE_W * 0.18, AVAILABLE_W * 0.77],
        caption='Table 5: Slash Commands Reference',
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 5: Code Editor
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('5. Code Editor'))

    story.extend(add_subsection('5.1 Multi-File Tabs'))
    story.append(body(
        'The code editor supports multiple open files displayed as tabs along the top of the '
        'editor area. Tabs can be reordered by dragging and dropping, and each tab shows the '
        'file name with an unsaved changes indicator (a dot icon) when modifications have not '
        'yet been saved. Closing a tab with unsaved changes will prompt a confirmation dialog.'
    ))

    story.extend(add_subsection('5.2 Syntax Highlighting'))
    story.append(body(
        'TeamForge IDE provides syntax highlighting for a wide range of programming languages '
        'and file formats. The editor displays line numbers along the left gutter, and syntax '
        'elements such as keywords, strings, comments, and types are color-coded for quick '
        'visual parsing. The color scheme follows the Catppuccin Mocha theme for a comfortable, '
        'low-eye-strain experience during extended coding sessions.'
    ))

    story.extend(add_subsection('5.3 Find and Replace'))
    story.append(body(
        'The built-in Find and Replace bar supports the following search modes:'
    ))
    find_items = [
        '<b>Regular Expression:</b> Toggle regex mode to search using pattern matching.',
        '<b>Case-Sensitive:</b> Toggle case sensitivity for exact-match searching.',
        '<b>Whole-Word:</b> Match only complete words, excluding partial matches.',
        '<b>Replace All:</b> Replace all occurrences at once, or step through matches one at a time.',
    ]
    for item in find_items:
        story.append(bullet(item))
    story.append(body(
        'Activate Find and Replace using <font name="DejaVuSans">Ctrl+F</font> for find-only '
        'mode, or <font name="DejaVuSans">Ctrl+H</font> for find and replace mode.'
    ))

    story.extend(add_subsection('5.4 Navigation'))
    story.append(body(
        'The editor provides several navigation features to help you move quickly through '
        'your codebase:'
    ))
    nav_items = [
        '<b>Go to Line (Ctrl+G):</b> Jump directly to a specific line number in the current file.',
        '<b>Global Search (Ctrl+Shift+F):</b> Search across all files in the project with result preview.',
        '<b>Breadcrumb Navigation:</b> Click on any segment of the breadcrumb path (folder / file / symbol) to navigate.',
        '<b>Tab Switching (Ctrl+Tab):</b> Cycle through open file tabs quickly.',
    ]
    for item in nav_items:
        story.append(bullet(item))

    story.extend(add_subsection('5.5 Run Current File'))
    story.append(body(
        'The Run Current File feature (<font name="DejaVuSans">Ctrl+Enter</font>) automatically '
        'detects the programming language of the active file and executes it with the appropriate '
        'runtime. The output is displayed in the bottom panel\'s terminal tab. Supported '
        'auto-detection includes: JavaScript/TypeScript (Node/Bun), Python, Shell scripts, and more. '
        'If the language cannot be determined, the system prompts for manual run command specification.'
    ))

    story.extend(add_subsection('5.6 Auto-Save'))
    story.append(body(
        'TeamForge IDE features automatic saving of file changes. When auto-save is enabled, '
        'modifications are saved after a brief idle period. Files with unsaved changes display '
        'a visual indicator (dot icon) on their tab. The auto-save interval can be configured '
        'in the Settings panel under Editor Preferences.'
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 6: Project Management
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('6. Project Management'))

    story.extend(add_subsection('6.1 Virtual File System'))
    story.append(body(
        'The Virtual File System (VFS) provides a complete file management interface within the '
        'browser, eliminating the need for local file system access. The VFS supports:'
    ))
    vfs_items = [
        '<b>Create Files:</b> Add new files with automatic type detection and boilerplate templates.',
        '<b>Create Directories:</b> Organize code with nested directory structures.',
        '<b>Edit Files:</b> Modify files directly in the code editor; changes are persisted to the VFS.',
        '<b>Delete Files/Directories:</b> Remove files or entire directories with confirmation prompts.',
        '<b>Batch Operations:</b> Perform create, update, or delete operations on multiple files simultaneously via the batch API endpoint.',
        '<b>Mkdir:</b> Create nested directory structures with a single API call.',
    ]
    for item in vfs_items:
        story.append(bullet(item))

    story.extend(add_subsection('6.2 Task Board'))
    story.append(body(
        'The integrated task board provides a Kanban-style interface for managing work items '
        'across six status columns, mirroring the software development lifecycle:'
    ))
    story.extend(make_table(
        ['Status', 'Description', 'Agent Assignment'],
        [
            ['Backlog', 'Newly created tasks awaiting triage and prioritization', 'Unassigned'],
            ['Todo', 'Prioritized tasks ready to be picked up by an agent', 'Auto-assigned'],
            ['In Progress', 'Tasks currently being worked on by an assigned agent', 'Assigned agent'],
            ['In Review', 'Completed tasks undergoing code review by Prism', 'Prism (Reviewer)'],
            ['Done', 'Tasks that have passed review and are complete', 'N/A'],
            ['Blocked', 'Tasks that cannot proceed due to dependencies or issues', 'Requires escalation'],
        ],
        col_widths=[AVAILABLE_W * 0.14, AVAILABLE_W * 0.50, AVAILABLE_W * 0.31],
        caption='Table 6: Task Board Status Columns',
    ))

    story.extend(add_subsection('6.3 Task Priority Levels'))
    story.extend(make_table(
        ['Priority', 'Color', 'Description'],
        [
            ['Critical', 'Red', 'Must be resolved immediately. Blocks other work or affects production.'],
            ['High', 'Orange', 'Important and should be addressed soon. Significant impact on progress.'],
            ['Medium', 'Yellow', 'Standard priority. No immediate urgency but should be planned.'],
            ['Low', 'Green', 'Nice-to-have items. Can be deferred without impacting core functionality.'],
        ],
        col_widths=[AVAILABLE_W * 0.15, AVAILABLE_W * 0.12, AVAILABLE_W * 0.68],
        caption='Table 7: Task Priority Levels',
    ))

    story.extend(add_subsection('6.4 Task Types'))
    story.extend(make_table(
        ['Type', 'Description', 'Typical Agent'],
        [
            ['Feature', 'New functionality or enhancement to existing features', 'Codey (Developer)'],
            ['Bugfix', 'Correction of defects or unexpected behavior', 'Codey (Developer)'],
            ['Refactor', 'Code restructuring without changing external behavior', 'Codey / Prism'],
            ['Test', 'Creation or improvement of test coverage', 'Flux (Tester)'],
            ['Docs', 'Documentation writing or updates', 'Nova (PM)'],
            ['Infra', 'Infrastructure or DevOps-related changes', 'Blaze (DevOps)'],
        ],
        col_widths=[AVAILABLE_W * 0.12, AVAILABLE_W * 0.55, AVAILABLE_W * 0.28],
        caption='Table 8: Task Types and Default Agent Assignments',
    ))

    story.extend(add_subsection('6.5 Auto-Assignment'))
    story.append(body(
        'The auto-assignment system matches tasks to agents based on task type and agent '
        'specialization. When a task is moved to "Todo" status, the orchestrator automatically '
        'assigns it to the most appropriate available agent. The assignment logic considers: '
        'task type to agent role mapping (as shown in Table 8), current agent workload and status, '
        'agent expertise level and past performance on similar tasks, and task priority -- critical '
        'and high-priority tasks are assigned first.'
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 7: Terminal and Build
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('7. Terminal and Build'))

    story.extend(add_subsection('7.1 Interactive Terminal'))
    story.append(body(
        'The built-in interactive terminal allows you to execute commands directly within the IDE. '
        'It provides a full command-line interface with the following capabilities: command '
        'execution with real-time output streaming, command history navigation using up/down arrow '
        'keys, working directory management, and process signal handling (interrupt, kill). '
        'The terminal is accessible from the bottom panel and can be toggled with keyboard shortcuts.'
    ))

    story.extend(add_subsection('7.2 Build, Lint, and Test Commands'))
    story.append(body(
        'TeamForge IDE integrates common development commands directly into the workflow:'
    ))
    blt_items = [
        '<b>Build:</b> Compile the project and report any errors. Results are displayed in the Build Logs tab.',
        '<b>Lint:</b> Run the configured linter (ESLint, Pylint, etc.) and display warnings and errors.',
        '<b>Test:</b> Execute the test suite and show results including pass/fail counts and coverage metrics.',
    ]
    for item in blt_items:
        story.append(bullet(item))

    story.extend(add_subsection('7.3 Pre-Deploy Checks'))
    story.append(body(
        'Before deployment, TeamForge IDE runs a series of pre-deploy checks to ensure code '
        'quality and readiness. These checks include: all tests passing with adequate coverage, '
        'no critical or high-severity linting errors, successful build completion, no uncommitted '
        'changes in the working directory (optional), and dependency security audit (if configured). '
        'Pre-deploy checks can be triggered manually or are automatically run by Blaze when '
        'initiating deployment.'
    ))

    story.extend(add_subsection('7.4 Command Whitelist'))
    story.append(body(
        'For security, the terminal operates with a command whitelist that restricts which '
        'commands can be executed. The default whitelist includes safe, read-only, and '
        'development commands. Commands outside the whitelist require explicit approval. '
        'The whitelist can be customized in the Settings panel under Security configuration. '
        'This prevents accidental execution of destructive commands such as <font name="DejaVuSans">'
        'rm -rf</font>, <font name="DejaVuSans">DROP TABLE</font>, or other system-altering operations.'
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 8: Settings and Configuration
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('8. Settings and Configuration'))

    story.extend(add_subsection('8.1 AI Provider Settings'))
    story.append(body(
        'Configure your preferred AI provider and model from the Settings panel. Each provider '
        'requires specific configuration:'
    ))
    provider_items = [
        '<b>Z-AI:</b> Requires an API key for the Z-AI platform. Select between GLM-4 (high quality) and GLM-4 Flash (low latency).',
        '<b>NVIDIA NIM:</b> Requires an NVIDIA API key. Choose from 80+ models across multiple model families.',
        '<b>OpenAI-Compatible:</b> Requires a base URL and optional API key. Configure the endpoint URL for your self-hosted or third-party service.',
    ]
    for item in provider_items:
        story.append(bullet(item))

    story.extend(add_subsection('8.2 Editor Preferences'))
    story.extend(make_table(
        ['Setting', 'Options', 'Default'],
        [
            ['Font Size', '10 - 24 pt', '14'],
            ['Tab Size', '2, 4, 8 spaces', '2'],
            ['Word Wrap', 'On / Off', 'On'],
            ['Minimap', 'Enabled / Disabled', 'Enabled'],
            ['Auto-Save', 'Enabled / Disabled', 'Enabled'],
            ['Auto-Save Delay', '500 - 5000 ms', '1000 ms'],
            ['Line Numbers', 'On / Off', 'On'],
            ['Bracket Pair Colorization', 'On / Off', 'On'],
        ],
        col_widths=[AVAILABLE_W * 0.30, AVAILABLE_W * 0.40, AVAILABLE_W * 0.25],
        caption='Table 9: Editor Preference Settings',
    ))

    story.extend(add_subsection('8.3 API Key Configuration'))
    story.append(body(
        'API keys are stored securely in the application configuration and are never exposed '
        'in client-side code. To configure an API key: open Settings, navigate to the AI Provider '
        'section, select your provider, enter the API key in the designated field, and click '
        '"Test Connection" to verify. API keys are transmitted over HTTPS and stored in encrypted '
        'environment variables on the server side.'
    ))

    story.extend(add_subsection('8.4 Connection Testing'))
    story.append(body(
        'Each AI provider configuration includes a "Test Connection" button that sends a '
        'test request to verify: API key validity and authentication, endpoint accessibility '
        'and response time, model availability and response quality. A successful test displays '
        'a green checkmark along with the response latency. A failed test shows the error '
        'message and suggested remediation steps.'
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 9: Keyboard Shortcuts
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('9. Keyboard Shortcuts'))
    story.append(body(
        'TeamForge IDE provides a comprehensive set of keyboard shortcuts for efficient workflow. '
        'The shortcuts overlay can be toggled at any time by pressing '
        '<font name="DejaVuSans">Ctrl+Shift+?</font> (or <font name="DejaVuSans">Cmd+Shift+?</font> on macOS).'
    ))
    story.extend(make_code_table(
        ['Shortcut', 'Action'],
        [
            ['Ctrl+S', 'Save current file'],
            ['Ctrl+Z', 'Undo'],
            ['Ctrl+Shift+Z', 'Redo'],
            ['Ctrl+F', 'Find in current file'],
            ['Ctrl+H', 'Find and Replace'],
            ['Ctrl+G', 'Go to Line'],
            ['Ctrl+Shift+F', 'Global Search across project'],
            ['Ctrl+Enter', 'Run current file'],
            ['Ctrl+P', 'Quick file open'],
            ['Ctrl+Tab', 'Switch to next tab'],
            ['Ctrl+Shift+Tab', 'Switch to previous tab'],
            ['Ctrl+W', 'Close current tab'],
            ['Ctrl+B', 'Toggle sidebar visibility'],
            ['Ctrl+J', 'Toggle bottom panel'],
            ['Ctrl+Shift+E', 'Focus file explorer'],
            ['Ctrl+Shift+P', 'Open command palette'],
            ['Ctrl+Shift+?', 'Show keyboard shortcuts overlay'],
            ['Ctrl+`', 'Toggle terminal panel'],
            ['Ctrl+N', 'New file'],
            ['Ctrl+Shift+N', 'New directory'],
            ['Ctrl+,', 'Open Settings'],
            ['Ctrl+K Ctrl+C', 'Toggle line comment'],
            ['Ctrl+K Ctrl+U', 'Remove line comment'],
            ['Alt+Up', 'Move line up'],
            ['Alt+Down', 'Move line down'],
        ],
        col_widths=[AVAILABLE_W * 0.25, AVAILABLE_W * 0.70],
        caption='Table 10: Keyboard Shortcuts',
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 10: API Reference
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('10. API Reference'))
    story.append(body(
        'TeamForge IDE exposes a RESTful API that allows programmatic access to all core '
        'features. The API is organized into the following resource groups:'
    ))

    story.extend(make_code_table(
        ['Endpoint', 'Methods', 'Description'],
        [
            ['/api/agents', 'GET, POST', 'List all agents or create a new agent task'],
            ['/api/agents/[id]', 'GET, PATCH, DELETE', 'Get, update, or delete a specific agent'],
            ['/api/tasks', 'GET, POST', 'List all tasks or create a new task'],
            ['/api/tasks/[id]', 'GET, PATCH, DELETE', 'Get, update, or delete a specific task'],
            ['/api/chat-sessions', 'GET, POST', 'List chat sessions or create a new session'],
            ['/api/chat-sessions/[id]', 'GET, PATCH, DELETE', 'Get, update, or delete a session'],
            ['/api/ai/chat', 'POST', 'Send a message to the AI and receive a streaming response'],
            ['/api/files', 'GET, POST', 'List files or create a new file in the VFS'],
            ['/api/files/[id]', 'GET, PATCH, DELETE', 'Get, update, or delete a specific file'],
            ['/api/execute', 'POST', 'Execute a command in the terminal'],
            ['/api/projects', 'GET, POST', 'List projects or create a new project'],
            ['/api/projects/[id]', 'GET, PATCH, DELETE', 'Get, update, or delete a project'],
            ['/api/projects/[id]/export', 'GET', 'Export project data as a downloadable archive'],
            ['/api/projects/import', 'POST', 'Import project data from an uploaded archive'],
            ['/api/vfs', 'GET, POST', 'Virtual file system read and write operations'],
            ['/api/vfs/mkdir', 'POST', 'Create a directory in the virtual file system'],
            ['/api/vfs/delete', 'POST', 'Delete a file or directory from the VFS'],
            ['/api/vfs/batch', 'POST', 'Batch file operations (create, update, delete multiple)'],
            ['/api/terminal', 'POST', 'Execute terminal commands with output streaming'],
            ['/api/agent-scheduler', 'GET, POST', 'View and manage the agent task scheduler'],
            ['/api/build-logs', 'GET', 'Retrieve recent build log entries'],
            ['/api/metrics', 'GET', 'System performance metrics and agent statistics'],
            ['/api/dashboard', 'GET', 'Dashboard summary data for the overview panel'],
            ['/api/git', 'GET, POST', 'Git operations (status, commit, push, pull)'],
        ],
        col_widths=[AVAILABLE_W * 0.30, AVAILABLE_W * 0.18, AVAILABLE_W * 0.47],
        caption='Table 11: REST API Endpoints',
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 11: AI Providers Reference
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('11. AI Providers Reference'))

    story.extend(add_subsection('11.1 Z-AI'))
    story.append(body(
        'Z-AI is the default AI provider for TeamForge IDE, offering models specifically '
        'optimized for software development tasks:'
    ))
    story.extend(make_table(
        ['Model', 'Context Window', 'Best For', 'Latency'],
        [
            ['GLM-4', '128K tokens', 'Complex reasoning, architecture design, multi-step code generation', 'Standard'],
            ['GLM-4 Flash', '128K tokens', 'Quick completions, simple edits, rapid prototyping', 'Low'],
        ],
        col_widths=[AVAILABLE_W * 0.16, AVAILABLE_W * 0.18, AVAILABLE_W * 0.48, AVAILABLE_W * 0.13],
        caption='Table 12: Z-AI Models',
    ))

    story.extend(add_subsection('11.2 NVIDIA NIM'))
    story.append(body(
        'NVIDIA NIM provides access to over 80 production-grade AI models through a unified API. '
        'The following model families are available:'
    ))
    story.extend(make_table(
        ['Model Family', 'Examples', 'Strengths'],
        [
            ['Meta Llama', 'Llama 3.1 8B/70B/405B', 'General-purpose, strong reasoning, open weights'],
            ['NVIDIA Nemotron', 'Nemotron 4 340B', 'NVIDIA-optimized, high accuracy on code tasks'],
            ['DeepSeek', 'DeepSeek-V2, DeepSeek-Coder', 'Exceptional code generation and understanding'],
            ['Mistral', 'Mistral 7B, Mixtral 8x22B', 'Efficient inference, strong multilingual support'],
            ['Qwen', 'Qwen 2 72B, Qwen 1.5 110B', 'Strong on Asian languages and code'],
            ['Google Gemma', 'Gemma 2 9B/27B', 'Lightweight, efficient for edge deployments'],
            ['Microsoft Phi', 'Phi-3 Mini/Small/Medium', 'Small but capable, ideal for constrained environments'],
        ],
        col_widths=[AVAILABLE_W * 0.18, AVAILABLE_W * 0.30, AVAILABLE_W * 0.47],
        caption='Table 13: NVIDIA NIM Model Families',
    ))

    story.extend(add_subsection('11.3 OpenAI-Compatible Endpoints'))
    story.append(body(
        'The OpenAI-Compatible provider allows TeamForge IDE to connect to any service that '
        'implements the OpenAI API format. Supported platforms include:'
    ))
    oai_items = [
        '<b>Ollama:</b> Run open-source models locally with GPU acceleration. Ideal for air-gapped environments or cost-sensitive workflows. Supports Llama, Mistral, Phi, and many other models.',
        '<b>LM Studio:</b> A desktop application for running local LLMs with a user-friendly interface. Provides OpenAI-compatible API endpoint for easy integration.',
        '<b>vLLM:</b> High-throughput inference server for production deployments. Supports continuous batching and PagedAttention for optimal GPU utilization.',
        '<b>Together AI:</b> Cloud-based inference platform offering access to open-source models at scale. Provides serverless endpoints with auto-scaling.',
    ]
    for item in oai_items:
        story.append(bullet(item))
    story.append(body(
        'To configure an OpenAI-Compatible provider, specify the base URL of the API endpoint '
        'and optionally provide an API key. The system automatically detects available models '
        'from the /v1/models endpoint.'
    ))

    # ═══════════════════════════════════════════════════
    # SECTION 12: Troubleshooting
    # ═══════════════════════════════════════════════════
    story.extend(add_major_section('12. Troubleshooting'))

    story.extend(add_subsection('12.1 Common Issues and Solutions'))
    story.extend(make_table(
        ['Issue', 'Cause', 'Solution'],
        [
            ['Application fails to start', 'Missing dependencies or incorrect Node version', 'Run bun install and verify Node.js 18+ is installed'],
            ['Database connection error', 'PostgreSQL not running or wrong credentials', 'Check DATABASE_URL in .env and ensure PostgreSQL is running'],
            ['Blank page on load', 'JavaScript build error', 'Clear browser cache and check console for errors'],
            ['Agents stuck in "Thinking"', 'AI provider unreachable or rate limited', 'Check API key validity and provider status; try a different model'],
            ['File changes not persisting', 'Auto-save disabled or VFS sync error', 'Enable auto-save in Settings; refresh the page to re-sync VFS'],
            ['Terminal commands not executing', 'Command blocked by whitelist', 'Check the command whitelist in Security settings and add the command'],
            ['Slow AI responses', 'Network latency or large context window', 'Switch to a faster model (GLM-4 Flash) or reduce context size'],
        ],
        col_widths=[AVAILABLE_W * 0.22, AVAILABLE_W * 0.33, AVAILABLE_W * 0.40],
        caption='Table 14: Common Issues and Solutions',
    ))

    story.extend(add_subsection('12.2 WebSocket Connection Issues'))
    story.append(body(
        'TeamForge IDE uses WebSocket connections for real-time features such as agent status '
        'updates, terminal output streaming, and live chat responses. If you experience '
        'connectivity issues:'
    ))
    ws_items = [
        '<b>Check proxy configuration:</b> Ensure your reverse proxy (Nginx, Caddy, etc.) is configured to support WebSocket upgrades with the appropriate headers (Upgrade, Connection).',
        '<b>Verify port access:</b> The WebSocket service runs on a dedicated port. Ensure it is not blocked by firewalls or network policies.',
        '<b>Connection timeout:</b> If the connection drops after idle periods, check the WebSocket keep-alive settings on both client and server.',
        '<b>Multiple tabs:</b> Opening the application in multiple browser tabs creates separate WebSocket connections. Each tab maintains its own session state.',
    ]
    for item in ws_items:
        story.append(bullet(item))

    story.extend(add_subsection('12.3 AI Provider Fallback'))
    story.append(body(
        'When the primary AI provider is unavailable, TeamForge IDE supports automatic fallback '
        'to a secondary provider. The fallback chain is configured in Settings under AI Providers. '
        'For example, if Z-AI is unreachable, the system can automatically route requests to '
        'NVIDIA NIM or your OpenAI-Compatible endpoint. The fallback behavior is as follows: '
        'the system attempts the primary provider first with a configurable timeout (default: 30 seconds). '
        'On timeout or error, the next provider in the chain is tried. If all providers fail, '
        'the user is notified with the specific error from each provider. Fallback events are '
        'logged in the System Log panel for debugging purposes.'
    ))

    # ─── BUILD ───
    doc.multiBuild(story)
    print(f"Body PDF built: {BODY_PDF}")


# ━━ RENDER COVER ━━
def render_cover():
    """Render the cover HTML to PDF using Playwright directly."""
    cover_js = f"""
const {{ chromium }} = require('playwright');
(async () => {{
  const browser = await chromium.launch({{ headless: true }});
  const page = await browser.newPage({{ viewport: {{ width: 794, height: 1200 }} }});
  await page.goto('file://{COVER_HTML}', {{ waitUntil: 'networkidle' }});
  const poster = await page.evaluate(() => {{
    const el = document.querySelector('.cover') || document.body;
    return {{ h: el.scrollHeight, w: el.scrollWidth }};
  }});
  console.log('Content size:', poster.w, 'x', poster.h);
  await page.pdf({{
    path: '{COVER_PDF}',
    width: '794px',
    height: poster.h + 'px',
    printBackground: true,
    margin: {{ top: '0', right: '0', bottom: '0', left: '0' }},
  }});
  await browser.close();
  console.log('Cover PDF generated!');
}})();
"""
    result = subprocess.run(
        ['node', '-e', cover_js],
        capture_output=True, text=True, timeout=60,
        cwd=str(OUTPUT_DIR),
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"Cover render stderr: {result.stderr}", file=sys.stderr)
        raise RuntimeError(f"Cover render failed: {result.stderr}")
    print(f"Cover PDF rendered: {COVER_PDF}")


# ━━ MERGE COVER + BODY ━━
def merge_pdfs():
    """Merge cover PDF as page 0 with body PDF using pypdf."""
    from pypdf import PdfReader, PdfWriter, Transformation

    A4_W, A4_H = 595.28, 841.89

    def normalize_page(page):
        box = page.mediabox
        w, h = float(box.width), float(box.height)
        if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
            sx, sy = A4_W / w, A4_H / h
            page.add_transformation(Transformation().scale(sx=sx, sy=sy))
            page.mediabox.lower_left = (0, 0)
            page.mediabox.upper_right = (A4_W, A4_H)
        return page

    writer = PdfWriter()
    # Cover as page 1
    cover_page = PdfReader(str(COVER_PDF)).pages[0]
    writer.add_page(normalize_page_to_a4(cover_page))
    # Body pages follow
    for page in PdfReader(str(BODY_PDF)).pages:
        writer.add_page(normalize_page_to_a4(page))

    writer.add_metadata({
        '/Title': 'TeamForge IDE Instruction Manual',
        '/Author': 'Z.ai',
        '/Creator': 'Z.ai',
        '/Subject': 'Instruction manual for TeamForge IDE v1.0.0',
    })
    with open(str(FINAL_PDF), 'wb') as f:
        writer.write(f)
    print(f"Final PDF merged: {FINAL_PDF}")


def normalize_page_to_a4(page):
    """Scale a page to A4 if its dimensions don't match."""
    from pypdf import Transformation
    A4_W, A4_H = 595.28, 841.89
    box = page.mediabox
    w, h = float(box.width), float(box.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        sx, sy = A4_W / w, A4_H / h
        page.add_transformation(Transformation().scale(sx=sx, sy=sy))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page


# ━━ MAIN ━━
if __name__ == '__main__':
    print("=" * 60)
    print("TeamForge IDE Instruction Manual - PDF Generator")
    print("=" * 60)

    # Step 1: Generate Cover HTML
    print("\n[1/4] Generating cover HTML...")
    generate_cover_html()

    # Step 2: Build Body PDF
    print("\n[2/4] Building body PDF...")
    build_body_pdf()

    # Step 3: Render Cover to PDF
    print("\n[3/4] Rendering cover PDF...")
    render_cover()

    # Step 4: Merge
    print("\n[4/4] Merging cover + body...")
    merge_pdfs()

    # Report
    size = os.path.getsize(str(FINAL_PDF))
    from pypdf import PdfReader
    reader = PdfReader(str(FINAL_PDF))
    pages = len(reader.pages)
    print(f"\n{'=' * 60}")
    print(f"DONE! Final PDF: {FINAL_PDF}")
    print(f"Size: {size / 1024:.1f} KB")
    print(f"Pages: {pages}")
    print(f"{'=' * 60}")
